### ISSUE TITLE
SCS automatically adds user and password to the base profile when doing APIML authentication

### ISSUE THREAD

**Issue by JirkaAichler** [zowe/zowe-cli-scs-plugin#43] opened 2021-06-16 07:59 UTC
**Steps to reproduce:**

1. Base profile before:
```
host: sys1.com
port: 1443
rejectUnauthorized: true
```
2.. Call `zowe auth login apiml --host sys1.com --port 60000 --user user1 --pass *****`
3. Base profile after without SCS:
```
host: sys1.com
port: 1443
rejectUnauthorized: true
tokenType: apimlAuthenticationToken
tokenValue: 1234
```
4. Base profile after with SCS:
```
host: sys1.com
port: 1443
rejectUnauthorized: true
user: 'managed by @zowe/secure-credential-store-for-zowe-cli'
password: 'managed by @zowe/secure-credential-store-for-zowe-cli'
tokenType: apimlAuthenticationToken
tokenValue: 'managed by @zowe/secure-credential-store-for-zowe-cli'
```

This is causing problems when using MFA since the credentials are not valid for the subsequent Zowe calls. Because
 you are not expecting not valid credentials to be in the profile, you will most likely suspend your account. 

Versions:
```
λ zowe --version
6.32.0

 -- pluginName: @zowe/secure-credential-store-for-zowe-cli
 -- package: @zowe/secure-credential-store-for-zowe-cli@zowe-v1-lts
 -- version: 4.1.5
 -- registry: https://registry.npmjs.org/
```

**Comment by t1m0thyj** [comment] 2021-06-16 20:29
What commands are you running between steps 3 and 4 to go from "without SCS" to "with SCS"?

I tried to reproduce the issue with the following commands and wasn't able to:
```
$ zowe plugins install @zowe/secure-credential-store-for-zowe-cli
...
This plugin was successfully validated. Enjoy the plugin.

$ zowe profiles create base test --host example.com --port 1443 --ru true
Profile created successfully! Path:
C:\Users\User\.zowe\profiles\base\test.yaml

host:               example.com
port:               1443
rejectUnauthorized: true

Review the created profile and edit if necessary using the profile update command.

$ zowe auth login apiml --host example.com --port 60004 --user XXX --pass XXX

Login successful. The authentication token is stored in the 'test' base profile for future use. To revoke this token and remove it from your profile, review the 'zowe auth logout' command.

$ cat ~/.zowe/profiles/base/test.yaml
host: example.com
port: 1443
rejectUnauthorized: true
tokenType: apimlAuthenticationToken
tokenValue: 'managed by @zowe/secure-credential-store-for-zowe-cli'

$ zowe --version
6.32.0

$ zowe plugins list

Installed plugins:
...
 -- pluginName: @zowe/secure-credential-store-for-zowe-cli
 -- package: @zowe/secure-credential-store-for-zowe-cli
 -- version: 4.1.5
 -- registry: https://registry.npmjs.org/
```

**Comment by JirkaAichler** [comment] 2021-06-17 06:02
I'll reply by email so I don't have to mask internal information.

There are no steps between steps 3 and 4.. I have tried that twice, with and without the plugin.

**Comment by t1m0thyj** [comment] 2021-07-09 17:06
The cause of this issue was "user" and "password" existed in the credential vault under old service IDs like:
* `@brightside/core`
* `Broadcom-Plugin`
* `@zowe/cli`
* `Zowe-Plugin`

These were left behind from old profiles, and deleting them resolved the issue.

It seems like there are potentially 2 bugs here:
1. `zowe auth login` shouldn't care that these properties exist in the Credential Manager and be affected by them.
2. If you ran a `zowe profiles update` command a while back to remove user and password from your base profile, it should have removed them from the Credential Manager as well.

**Comment by zFernand0** [comment] 2023-03-07 14:52
Closing in favor of the two issues created

**Closed by zFernand0** 2023-03-07 14:52 UTC
